version: '3'

services:
  web:
    build:
      context:  .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    container_name: ciscodjango
    volumes:
      - .:/ciscodjango
    ports:
      - "9000:9000"
